package database

// AUTOGENERATED. DO NOT EDIT.

import (
	. "github.com/knq/chromedp/cdp"
)

var (
	_ BackendNode
	_ BackendNodeID
	_ ComputedProperty
	_ ErrorType
	_ Frame
	_ FrameID
	_ LoaderID
	_ Message
	_ MessageError
	_ MethodType
	_ Node
	_ NodeID
	_ NodeType
	_ PseudoType
	_ RGBA
	_ ShadowRootType
	_ Timestamp
)

// DatabaseID unique identifier of Database object.
type DatabaseID string

// String returns the DatabaseID as string value.
func (t DatabaseID) String() string {
	return string(t)
}

// Database database object.
type Database struct {
	ID      DatabaseID `json:"id,omitempty"`      // Database ID.
	Domain  string     `json:"domain,omitempty"`  // Database domain.
	Name    string     `json:"name,omitempty"`    // Database name.
	Version string     `json:"version,omitempty"` // Database version.
}

// Error database error.
type Error struct {
	Message string `json:"message,omitempty"` // Error message.
	Code    int64  `json:"code,omitempty"`    // Error code.
}
