// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  page

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( AddScriptToEvaluateOnNewDocumentParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AddScriptToEvaluateOnNewDocumentParams ) UnmarshalJSON([]byte) error { return nil }
func ( AddScriptToEvaluateOnNewDocumentParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AddScriptToEvaluateOnNewDocumentParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AddScriptToEvaluateOnNewDocumentParams *AddScriptToEvaluateOnNewDocumentParams

func ( AddScriptToEvaluateOnNewDocumentReturns ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AddScriptToEvaluateOnNewDocumentReturns ) UnmarshalJSON([]byte) error { return nil }
func ( AddScriptToEvaluateOnNewDocumentReturns ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AddScriptToEvaluateOnNewDocumentReturns ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AddScriptToEvaluateOnNewDocumentReturns *AddScriptToEvaluateOnNewDocumentReturns

func ( AppManifestError ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AppManifestError ) UnmarshalJSON([]byte) error { return nil }
func ( AppManifestError ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AppManifestError ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AppManifestError *AppManifestError

func ( BringToFrontParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* BringToFrontParams ) UnmarshalJSON([]byte) error { return nil }
func ( BringToFrontParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BringToFrontParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BringToFrontParams *BringToFrontParams

func ( CaptureScreenshotParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CaptureScreenshotParams ) UnmarshalJSON([]byte) error { return nil }
func ( CaptureScreenshotParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CaptureScreenshotParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CaptureScreenshotParams *CaptureScreenshotParams

func ( CaptureScreenshotReturns ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CaptureScreenshotReturns ) UnmarshalJSON([]byte) error { return nil }
func ( CaptureScreenshotReturns ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CaptureScreenshotReturns ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CaptureScreenshotReturns *CaptureScreenshotReturns

func ( CreateIsolatedWorldParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CreateIsolatedWorldParams ) UnmarshalJSON([]byte) error { return nil }
func ( CreateIsolatedWorldParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CreateIsolatedWorldParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CreateIsolatedWorldParams *CreateIsolatedWorldParams

func ( CreateIsolatedWorldReturns ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* CreateIsolatedWorldReturns ) UnmarshalJSON([]byte) error { return nil }
func ( CreateIsolatedWorldReturns ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CreateIsolatedWorldReturns ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CreateIsolatedWorldReturns *CreateIsolatedWorldReturns

func ( DisableParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* DisableParams ) UnmarshalJSON([]byte) error { return nil }
func ( DisableParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* DisableParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DisableParams *DisableParams

func ( EnableParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EnableParams ) UnmarshalJSON([]byte) error { return nil }
func ( EnableParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EnableParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EnableParams *EnableParams

func ( EventDomContentEventFired ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventDomContentEventFired ) UnmarshalJSON([]byte) error { return nil }
func ( EventDomContentEventFired ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventDomContentEventFired ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventDomContentEventFired *EventDomContentEventFired

func ( EventFrameAttached ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventFrameAttached ) UnmarshalJSON([]byte) error { return nil }
func ( EventFrameAttached ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventFrameAttached ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventFrameAttached *EventFrameAttached

func ( EventFrameClearedScheduledNavigation ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventFrameClearedScheduledNavigation ) UnmarshalJSON([]byte) error { return nil }
func ( EventFrameClearedScheduledNavigation ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventFrameClearedScheduledNavigation ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventFrameClearedScheduledNavigation *EventFrameClearedScheduledNavigation

func ( EventFrameDetached ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventFrameDetached ) UnmarshalJSON([]byte) error { return nil }
func ( EventFrameDetached ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventFrameDetached ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventFrameDetached *EventFrameDetached

func ( EventFrameNavigated ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventFrameNavigated ) UnmarshalJSON([]byte) error { return nil }
func ( EventFrameNavigated ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventFrameNavigated ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventFrameNavigated *EventFrameNavigated

func ( EventFrameResized ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventFrameResized ) UnmarshalJSON([]byte) error { return nil }
func ( EventFrameResized ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventFrameResized ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventFrameResized *EventFrameResized

func ( EventFrameScheduledNavigation ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventFrameScheduledNavigation ) UnmarshalJSON([]byte) error { return nil }
func ( EventFrameScheduledNavigation ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventFrameScheduledNavigation ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventFrameScheduledNavigation *EventFrameScheduledNavigation

func ( EventFrameStartedLoading ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventFrameStartedLoading ) UnmarshalJSON([]byte) error { return nil }
func ( EventFrameStartedLoading ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventFrameStartedLoading ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventFrameStartedLoading *EventFrameStartedLoading

func ( EventFrameStoppedLoading ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventFrameStoppedLoading ) UnmarshalJSON([]byte) error { return nil }
func ( EventFrameStoppedLoading ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventFrameStoppedLoading ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventFrameStoppedLoading *EventFrameStoppedLoading

func ( EventInterstitialHidden ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventInterstitialHidden ) UnmarshalJSON([]byte) error { return nil }
func ( EventInterstitialHidden ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventInterstitialHidden ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventInterstitialHidden *EventInterstitialHidden

func ( EventInterstitialShown ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventInterstitialShown ) UnmarshalJSON([]byte) error { return nil }
func ( EventInterstitialShown ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventInterstitialShown ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventInterstitialShown *EventInterstitialShown

func ( EventJavascriptDialogClosed ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventJavascriptDialogClosed ) UnmarshalJSON([]byte) error { return nil }
func ( EventJavascriptDialogClosed ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventJavascriptDialogClosed ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventJavascriptDialogClosed *EventJavascriptDialogClosed

func ( EventJavascriptDialogOpening ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventJavascriptDialogOpening ) UnmarshalJSON([]byte) error { return nil }
func ( EventJavascriptDialogOpening ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventJavascriptDialogOpening ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventJavascriptDialogOpening *EventJavascriptDialogOpening

func ( EventLifecycleEvent ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventLifecycleEvent ) UnmarshalJSON([]byte) error { return nil }
func ( EventLifecycleEvent ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventLifecycleEvent ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventLifecycleEvent *EventLifecycleEvent

func ( EventLoadEventFired ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventLoadEventFired ) UnmarshalJSON([]byte) error { return nil }
func ( EventLoadEventFired ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventLoadEventFired ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventLoadEventFired *EventLoadEventFired

func ( EventScreencastFrame ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventScreencastFrame ) UnmarshalJSON([]byte) error { return nil }
func ( EventScreencastFrame ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventScreencastFrame ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventScreencastFrame *EventScreencastFrame

func ( EventScreencastVisibilityChanged ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* EventScreencastVisibilityChanged ) UnmarshalJSON([]byte) error { return nil }
func ( EventScreencastVisibilityChanged ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* EventScreencastVisibilityChanged ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_EventScreencastVisibilityChanged *EventScreencastVisibilityChanged

func ( FrameResource ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* FrameResource ) UnmarshalJSON([]byte) error { return nil }
func ( FrameResource ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* FrameResource ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FrameResource *FrameResource

func ( FrameResourceTree ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* FrameResourceTree ) UnmarshalJSON([]byte) error { return nil }
func ( FrameResourceTree ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* FrameResourceTree ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FrameResourceTree *FrameResourceTree

func ( GetAppManifestParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetAppManifestParams ) UnmarshalJSON([]byte) error { return nil }
func ( GetAppManifestParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetAppManifestParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetAppManifestParams *GetAppManifestParams

func ( GetAppManifestReturns ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetAppManifestReturns ) UnmarshalJSON([]byte) error { return nil }
func ( GetAppManifestReturns ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetAppManifestReturns ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetAppManifestReturns *GetAppManifestReturns

func ( GetLayoutMetricsParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetLayoutMetricsParams ) UnmarshalJSON([]byte) error { return nil }
func ( GetLayoutMetricsParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetLayoutMetricsParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetLayoutMetricsParams *GetLayoutMetricsParams

func ( GetLayoutMetricsReturns ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetLayoutMetricsReturns ) UnmarshalJSON([]byte) error { return nil }
func ( GetLayoutMetricsReturns ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetLayoutMetricsReturns ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetLayoutMetricsReturns *GetLayoutMetricsReturns

func ( GetNavigationHistoryParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetNavigationHistoryParams ) UnmarshalJSON([]byte) error { return nil }
func ( GetNavigationHistoryParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetNavigationHistoryParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetNavigationHistoryParams *GetNavigationHistoryParams

func ( GetNavigationHistoryReturns ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetNavigationHistoryReturns ) UnmarshalJSON([]byte) error { return nil }
func ( GetNavigationHistoryReturns ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetNavigationHistoryReturns ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetNavigationHistoryReturns *GetNavigationHistoryReturns

func ( GetResourceContentParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetResourceContentParams ) UnmarshalJSON([]byte) error { return nil }
func ( GetResourceContentParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetResourceContentParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetResourceContentParams *GetResourceContentParams

func ( GetResourceContentReturns ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetResourceContentReturns ) UnmarshalJSON([]byte) error { return nil }
func ( GetResourceContentReturns ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetResourceContentReturns ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetResourceContentReturns *GetResourceContentReturns

func ( GetResourceTreeParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetResourceTreeParams ) UnmarshalJSON([]byte) error { return nil }
func ( GetResourceTreeParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetResourceTreeParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetResourceTreeParams *GetResourceTreeParams

func ( GetResourceTreeReturns ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* GetResourceTreeReturns ) UnmarshalJSON([]byte) error { return nil }
func ( GetResourceTreeReturns ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* GetResourceTreeReturns ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_GetResourceTreeReturns *GetResourceTreeReturns

func ( HandleJavaScriptDialogParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* HandleJavaScriptDialogParams ) UnmarshalJSON([]byte) error { return nil }
func ( HandleJavaScriptDialogParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* HandleJavaScriptDialogParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_HandleJavaScriptDialogParams *HandleJavaScriptDialogParams

func ( LayoutViewport ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* LayoutViewport ) UnmarshalJSON([]byte) error { return nil }
func ( LayoutViewport ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* LayoutViewport ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_LayoutViewport *LayoutViewport

func ( NavigateParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NavigateParams ) UnmarshalJSON([]byte) error { return nil }
func ( NavigateParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NavigateParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NavigateParams *NavigateParams

func ( NavigateReturns ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NavigateReturns ) UnmarshalJSON([]byte) error { return nil }
func ( NavigateReturns ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NavigateReturns ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NavigateReturns *NavigateReturns

func ( NavigateToHistoryEntryParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NavigateToHistoryEntryParams ) UnmarshalJSON([]byte) error { return nil }
func ( NavigateToHistoryEntryParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NavigateToHistoryEntryParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NavigateToHistoryEntryParams *NavigateToHistoryEntryParams

func ( NavigationEntry ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* NavigationEntry ) UnmarshalJSON([]byte) error { return nil }
func ( NavigationEntry ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* NavigationEntry ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_NavigationEntry *NavigationEntry

func ( PrintToPDFParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PrintToPDFParams ) UnmarshalJSON([]byte) error { return nil }
func ( PrintToPDFParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PrintToPDFParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PrintToPDFParams *PrintToPDFParams

func ( PrintToPDFReturns ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* PrintToPDFReturns ) UnmarshalJSON([]byte) error { return nil }
func ( PrintToPDFReturns ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* PrintToPDFReturns ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_PrintToPDFReturns *PrintToPDFReturns

func ( ReloadParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ReloadParams ) UnmarshalJSON([]byte) error { return nil }
func ( ReloadParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ReloadParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ReloadParams *ReloadParams

func ( RemoveScriptToEvaluateOnNewDocumentParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* RemoveScriptToEvaluateOnNewDocumentParams ) UnmarshalJSON([]byte) error { return nil }
func ( RemoveScriptToEvaluateOnNewDocumentParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* RemoveScriptToEvaluateOnNewDocumentParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RemoveScriptToEvaluateOnNewDocumentParams *RemoveScriptToEvaluateOnNewDocumentParams

func ( RequestAppBannerParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* RequestAppBannerParams ) UnmarshalJSON([]byte) error { return nil }
func ( RequestAppBannerParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* RequestAppBannerParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_RequestAppBannerParams *RequestAppBannerParams

func ( ScreencastFrameAckParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ScreencastFrameAckParams ) UnmarshalJSON([]byte) error { return nil }
func ( ScreencastFrameAckParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ScreencastFrameAckParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ScreencastFrameAckParams *ScreencastFrameAckParams

func ( ScreencastFrameMetadata ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* ScreencastFrameMetadata ) UnmarshalJSON([]byte) error { return nil }
func ( ScreencastFrameMetadata ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ScreencastFrameMetadata ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ScreencastFrameMetadata *ScreencastFrameMetadata

func ( SearchInResourceParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SearchInResourceParams ) UnmarshalJSON([]byte) error { return nil }
func ( SearchInResourceParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SearchInResourceParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SearchInResourceParams *SearchInResourceParams

func ( SearchInResourceReturns ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SearchInResourceReturns ) UnmarshalJSON([]byte) error { return nil }
func ( SearchInResourceReturns ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SearchInResourceReturns ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SearchInResourceReturns *SearchInResourceReturns

func ( SetAdBlockingEnabledParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SetAdBlockingEnabledParams ) UnmarshalJSON([]byte) error { return nil }
func ( SetAdBlockingEnabledParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SetAdBlockingEnabledParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SetAdBlockingEnabledParams *SetAdBlockingEnabledParams

func ( SetAutoAttachToCreatedPagesParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SetAutoAttachToCreatedPagesParams ) UnmarshalJSON([]byte) error { return nil }
func ( SetAutoAttachToCreatedPagesParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SetAutoAttachToCreatedPagesParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SetAutoAttachToCreatedPagesParams *SetAutoAttachToCreatedPagesParams

func ( SetDocumentContentParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SetDocumentContentParams ) UnmarshalJSON([]byte) error { return nil }
func ( SetDocumentContentParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SetDocumentContentParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SetDocumentContentParams *SetDocumentContentParams

func ( SetDownloadBehaviorParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SetDownloadBehaviorParams ) UnmarshalJSON([]byte) error { return nil }
func ( SetDownloadBehaviorParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SetDownloadBehaviorParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SetDownloadBehaviorParams *SetDownloadBehaviorParams

func ( StartScreencastParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* StartScreencastParams ) UnmarshalJSON([]byte) error { return nil }
func ( StartScreencastParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* StartScreencastParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_StartScreencastParams *StartScreencastParams

func ( StopLoadingParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* StopLoadingParams ) UnmarshalJSON([]byte) error { return nil }
func ( StopLoadingParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* StopLoadingParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_StopLoadingParams *StopLoadingParams

func ( StopScreencastParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* StopScreencastParams ) UnmarshalJSON([]byte) error { return nil }
func ( StopScreencastParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* StopScreencastParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_StopScreencastParams *StopScreencastParams

func ( Viewport ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Viewport ) UnmarshalJSON([]byte) error { return nil }
func ( Viewport ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Viewport ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Viewport *Viewport

func ( VisualViewport ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* VisualViewport ) UnmarshalJSON([]byte) error { return nil }
func ( VisualViewport ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* VisualViewport ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_VisualViewport *VisualViewport
