package io

// Code generated by chromedp-gen. DO NOT EDIT.

// StreamHandle [no description].
type StreamHandle string

// String returns the StreamHandle as string value.
func (t StreamHandle) String() string {
	return string(t)
}
