package cachestorage

// AUTOGENERATED. DO NOT EDIT.

import (
	. "github.com/knq/chromedp/cdp"
)

var (
	_ BackendNode
	_ BackendNodeID
	_ ComputedProperty
	_ ErrorType
	_ Frame
	_ FrameID
	_ LoaderID
	_ Message
	_ MessageError
	_ MethodType
	_ Node
	_ NodeID
	_ NodeType
	_ PseudoType
	_ RGBA
	_ ShadowRootType
	_ Timestamp
)

// CacheID unique identifier of the Cache object.
type CacheID string

// String returns the CacheID as string value.
func (t CacheID) String() string {
	return string(t)
}

// DataEntry data entry.
type DataEntry struct {
	Request  string `json:"request,omitempty"`  // Request url spec.
	Response string `json:"response,omitempty"` // Response stataus text.
}

// Cache cache identifier.
type Cache struct {
	CacheID        CacheID `json:"cacheId,omitempty"`        // An opaque unique id of the cache.
	SecurityOrigin string  `json:"securityOrigin,omitempty"` // Security origin of the cache.
	CacheName      string  `json:"cacheName,omitempty"`      // The name of the cache.
}
