package animation

// AUTOGENERATED. DO NOT EDIT.

import (
	. "github.com/knq/chromedp/cdp"
)

var (
	_ BackendNode
	_ BackendNodeID
	_ ComputedProperty
	_ ErrorType
	_ Frame
	_ FrameID
	_ LoaderID
	_ Message
	_ MessageError
	_ MethodType
	_ Node
	_ NodeID
	_ NodeType
	_ PseudoType
	_ RGBA
	_ ShadowRootType
	_ Timestamp
)

// EventAnimationCreated event for each animation that has been created.
type EventAnimationCreated struct {
	ID string `json:"id,omitempty"` // Id of the animation that was created.
}

// EventAnimationStarted event for animation that has been started.
type EventAnimationStarted struct {
	Animation *Animation `json:"animation,omitempty"` // Animation that was started.
}

// EventAnimationCanceled event for when an animation has been cancelled.
type EventAnimationCanceled struct {
	ID string `json:"id,omitempty"` // Id of the animation that was cancelled.
}

// EventTypes is all event types in the domain.
var EventTypes = []MethodType{
	EventAnimationAnimationCreated,
	EventAnimationAnimationStarted,
	EventAnimationAnimationCanceled,
}
