on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Install Packages
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y build-essential
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        TMPDIR=$RUNNER_TEMP go test -v ./...
        ./contrib/docker-test.sh
