name: Validate that using docker always works with the latest headless shell

on:
  push:
    branches:
      - master
      - PR/** # Build on any branch named PR/<something> from https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - '1.22.3'
    env:
      GO111MODULE: "on"
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '${{ matrix.go }}'

    - name: Print docker version
      run: docker version

    - name: Start headless-shell v125.0.6422.142
      run: docker run -d -t -p 9222:9222 --name chromedp-125.0.6422.142 chromedp/headless-shell:125.0.6422.142

    - name: Grep for network v125.0.6422.142 is listening on
      run: docker exec chromedp-125.0.6422.142 bash -c 'apt -qq update && apt install -qq -y iproute2 > /dev/null 2>&1 && ss -a | grep 9222'

    - name: Curl to v125.0.6422.142 of headless-shell
      run: curl -v http://localhost:9222/json/version

    - name: Start headless-shell at latest
      run: docker run -d -t -p 9222:9222 --name chromedp-latest chromedp/headless-shell:latest

    - name: Grep for network vlatest is listening on
      run: docker exec chromedp-latest bash -c 'apt -qq update && apt install -qq -y iproute2 > /dev/null 2>&1 && ss -a | grep 9222'

    - name: Curl to latest headless-shell - we expect this to fail
      run: curl -v http://localhost:9222/json/version

    - name: Stop containers
      if: always()
      run: |
        docker stop chromedp-125.0.6422.142
        docker rm chromedp-125.0.6422.142
        docker stop chromedp-latest
        docker rm chromedp-latest
