package serviceworker

// Code generated by chromedp-gen. DO NOT EDIT.

import (
	cdp "github.com/knq/chromedp/cdp"
)

// EventWorkerErrorReported [no description].
type EventWorkerErrorReported struct {
	ErrorMessage *ErrorMessage `json:"errorMessage"`
}

// EventWorkerRegistrationUpdated [no description].
type EventWorkerRegistrationUpdated struct {
	Registrations []*Registration `json:"registrations"`
}

// EventWorkerVersionUpdated [no description].
type EventWorkerVersionUpdated struct {
	Versions []*Version `json:"versions"`
}

// EventTypes all event types in the domain.
var EventTypes = []cdp.MethodType{
	cdp.EventServiceWorkerWorkerErrorReported,
	cdp.EventServiceWorkerWorkerRegistrationUpdated,
	cdp.EventServiceWorkerWorkerVersionUpdated,
}
